version: "3.1"

services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "3000:3000" 
    env_file: ./.env
    environment:
      - ENV=production
